# -*- coding: utf-8 -*-
"""Summarize.ipynb

Automatically generated by Colaboratory.

Original file is located at
  https://colab.research.google.com/drive/1l3xRjxAv45AC3yi6axj4LT6yB_pQ8jOS?usp=sharing
"""

# Description: This program aims to scrape and summarize news articles

#Install
#pip install nltk
#pip install newspaper3k

#Import the libraries
import nltk
from newspaper import Article
import textwrap

#Get the article
url = input('Enter the URL of the article: \n')
article = Article(url)

#Do some Natural Language Processing
print()
print('======================================================================')
article.download()
article.parse()
nltk.download('punkt')
article.nlp()
print('======================================================================')
print()

#Get title
title = article.title

#Get the author/s of the article
authors = article.authors

#Get the pubplished date
date = article.publish_date

#Get the article's text
#print(article.text)

#Get a summary of the article
summary = article.summary

#Final output
print()
print(title)
print()

if len(authors)>1:
  print('By',', '.join(authors))
else:
  print("Author's name not found")

try:
  print(date.strftime("%x"))
except:
  print("Date not found")
print()

# Wrap the summary. 
wrapper = textwrap.TextWrapper(width=100)   
word_list = wrapper.wrap(text=summary) 
  
# Print each line from summary 
for element in word_list: 
    print(element) 

print()
try:
  #Get the top image
  image = article.top_image
  from IPython.display import Image
  display(Image(url=image, width = 500, unconfined= True))
except:
  print('Unable to display image')